---

- hosts: all
  become: true
  tasks:

  - name: update repository index on Debian/Ubuntu
    apt:
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: upgrade repository on Debin/Ubuntu
    apt:
      upgrade: dist
    when: ansible_distribution in ["Debian", "ubuntu"]

  - name: install apache2 package on Debian/Ubuntu
    apt:
      name: apache2
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: add php support for apache on Debian/Ubuntu
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: update repository index on CentOS
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: upgrade repository on CentOS
    dnf:
      upgrade: dist
    when: ansible_distribution == "CentOS"

  - name: install apache2 package on CentOS
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution == "CentOS"

  - name: add php support for apache on CentOS
    dnf:
      name: php
      state: latest
    when: ansible_distribution == "CentOS"
