---

- hosts: all
  become: true
  tasks:

  - name: update and upgrade repository index on Debian/Ubuntu
    apt:
      update_cache: yes
      upgrade: dist
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: update and upgrade repository index on CentOS
    dnf:
      update_cache: yes
      state: latest
    when: ansible_distribution == "CentOS"
